async function runBatch(label='自动完成所选',stages=['script','voices','generate','qa']){if(!selected.size){toast('请先选择至少一集');return}if(!backend.online){toast(`${label}：已加入 ${selected.size} 集`);selected.clear();renderChapters();return}try{const job=await VoiceBookAPI.createJob(backend.projectId,{chapter_ids:[...selected],stages,force:label.includes('重新'),...apiJobSettings()});backend.activeJobId=job.id;selected.clear();renderChapters();toast(`${label}：任务已创建`);pollJob(job.id)}catch(e){toast(`任务创建失败：${e.message}`,true)}}
async function pollJob(jobId){if(!backend.online||!jobId)return;$('#active-run').style.display='flex';try{const job=await VoiceBookAPI.getJob(backend.projectId,jobId),percent=Math.round((job.progress||0)*100);$('.run-title b').textContent=job.status==='completed'?'批量任务已完成':job.status==='failed'?'批量任务失败':'正在处理章节';$('.run-title span').textContent=job.current_stage||job.status;$('.run-main p').textContent=job.message||'';$('.run-progress span').style.width=`${percent}%`;$('.run-progress small').textContent=`${percent}%`;if(['completed','failed','cancelled'].includes(job.status)){backend.activeJobId=null;if(job.status==='failed')toast(job.error||job.message,true);else toast('任务已完成');await loadProject(backend.projectId);return}setTimeout(()=>pollJob(jobId),1200)}catch(e){toast(`读取任务失败：${e.message}`,true)}}
function simulateGeneration(){const button=$('#start-generation');let pct=0;button.disabled=true;const timer=setInterval(()=>{pct+=5;const ring=$('.round-progress');ring.style.background=`conic-gradient(var(--accent) ${pct}%,var(--track) 0)`;$('span',ring).textContent=`${pct}%`;$('#generation-log').textContent=`演示生成 ${Math.ceil(246*pct/100)} / 246`;if(pct>=100){clearInterval(timer);button.disabled=false;toast('演示生成完成')}},100)}
async function startGeneration(){if(!backend.online||!currentEpisode?.backendId){simulateGeneration();return}try{const job=await VoiceBookAPI.createJob(backend.projectId,{chapter_ids:[currentEpisode.backendId],stages:['generate'],force:false,...apiJobSettings()});backend.activeJobId=job.id;$('#generation-log').textContent='任务已创建，正在等待 IndexTTS…';pollEpisodeGeneration(job.id)}catch(e){toast(e.message,true)}}
async function pollEpisodeGeneration(jobId){const job=await VoiceBookAPI.getJob(backend.projectId,jobId),pct=Math.round((job.progress||0)*100),ring=$('.round-progress');ring.style.background=`conic-gradient(var(--accent) ${pct}%,var(--track) 0)`;$('span',ring).textContent=`${pct}%`;$('#generation-log').textContent=job.message||job.status;if(job.status==='completed'){toast('本集音频已生成');await loadProject(backend.projectId);const updated=chapters.find(c=>c.backendId===currentEpisode.backendId);if(updated)currentEpisode=updated;showStage('qa');return}if(job.status==='failed'){toast(job.error||job.message,true);return}setTimeout(()=>pollEpisodeGeneration(jobId),1200)}
function buildWaveform(){$('#waveform').innerHTML=Array.from({length:70},(_,i)=>`<i style="height:${9+Math.abs(Math.sin(i*.72))*29}px"></i>`).join('')}
window.addEventListener('scroll',()=>$('.topbar').classList.toggle('scrolled',window.scrollY>4));
$('#mobile-menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#back-project').onclick=backProject;
$$('[data-stage]').forEach(b=>b.onclick=()=>showStage(b.dataset.stage));$$('[data-open]').forEach(b=>b.onclick=()=>openLayer(b.dataset.open));$$('.close-layer').forEach(b=>b.onclick=closeLayer);
$('#scrim').onclick=()=>{$('#sidebar').classList.remove('open');closeLayer()};$('#chapter-search').oninput=renderChapters;$('#chapter-filter').onchange=renderChapters;
$('#select-all').onchange=e=>{$$('.chapter-row').forEach(r=>e.target.checked?selected.add(r.dataset.chapter):selected.delete(r.dataset.chapter));renderChapters()};$('#clear-selection').onclick=()=>{selected.clear();renderChapters()};
$('#batch-run').onclick=()=>runBatch();$('#batch-analyze').onclick=()=>runBatch('重新分析所选',['script','voices']);$('#top-primary').onclick=()=>$('#episode-screen').classList.contains('active')?$('#confirm-stage').click():runBatch();
$('#pause-run').onclick=async()=>{if(backend.online&&backend.activeJobId)try{await VoiceBookAPI.cancelJob(backend.projectId,backend.activeJobId);toast('已请求取消当前任务')}catch(e){toast(e.message,true)}else toast('当前没有可取消的后端任务')};
$$('[data-script-filter]').forEach(b=>b.onclick=()=>{$$('[data-script-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderScript(b.dataset.scriptFilter)});
$('#save-line').onclick=async()=>{const r=scriptRows.find(x=>x.id===$('#save-line').dataset.line);if(!r)return;const update={speaker:$('#speaker-select').value,emotion:$('#emotion-select').value,text:$('#line-text').value,confidence:97,needs_review:false};try{if(backend.online&&currentEpisode.backendId)await VoiceBookAPI.updateSegment(backend.projectId,currentEpisode.backendId,r.id,update);Object.assign(r,{speaker:update.speaker,emotion:update.emotion,text:update.text,conf:97,attention:false});renderScript('attention');toast('片段已确认并保存')}catch(e){toast(e.message,true)}};
$('#rerun-line').onclick=()=>toast('请使用“重跑当前环节”重新执行本章角色拆分');$$('.mode-row').forEach(b=>b.onclick=()=>{$$('.mode-row').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#generation-mode').value=b.dataset.mode;toast(b.dataset.mode==='ordered'?'已选择按原文顺序':'已选择按角色连续调度')});
$('#start-generation').onclick=startGeneration;
$('#confirm-stage').onclick=async()=>{const steps=$$('.stage-step'),idx=steps.findIndex(s=>s.dataset.stage===activeStage);try{if(backend.online&&currentEpisode.backendId)await VoiceBookAPI.confirmStage(backend.projectId,currentEpisode.backendId,activeStage);if(idx<steps.length-1){showStage(steps[idx+1].dataset.stage);toast('当前环节已确认')}else{toast('本集已标记完成');await loadProject(backend.projectId)}}catch(e){toast(e.message,true)}};
$('#rerun-stage').onclick=async()=>{if(!backend.online||!currentEpisode?.backendId){toast(`演示重跑：${$('.stage-step.current b').textContent}`);return}try{const job=await VoiceBookAPI.createJob(backend.projectId,{chapter_ids:[currentEpisode.backendId],stages:[activeStage],force:true,...apiJobSettings()});backend.activeJobId=job.id;toast('已创建重跑任务');pollEpisodeGeneration(job.id)}catch(e){toast(e.message,true)}};
$('#ai-match').onclick=async()=>{try{if(backend.online){const p=await VoiceBookAPI.autoMatch(backend.projectId,false);backend.project=p;characters=Object.values(p.roles||{}).map(mapRole)}else characters.forEach(c=>{if(c.score.includes('待'))c.score='92% 匹配'});renderVoiceDrawer();renderEpisodeVoices();toast('AI 已完成全局音色匹配，并避开已占用音色')}catch(e){toast(e.message,true)}};
$('#browse-files').onclick=()=>$('#chapter-files').click();$('#chapter-files').onchange=e=>{$('#mock-import').textContent=e.target.files.length?`导入 ${e.target.files.length} 个文件`:'导入所选文件'};
$('#mock-import').onclick=async()=>{const files=$('#chapter-files').files;if(!files.length){toast('请先选择 TXT 文件');return}try{if(!backend.online)throw new Error('后端未连接');await VoiceBookAPI.uploadChapters(backend.projectId,files);closeLayer();$('#chapter-files').value='';await loadProject(backend.projectId);toast('章节已导入')}catch(e){toast(e.message,true)}};
$('#create-project').onclick=async()=>{const name=$('#new-project-name').value.trim();if(!name){toast('请输入项目名称');return}try{if(!backend.online)throw new Error('后端未连接');const p=await VoiceBookAPI.createProject({name,source_path:$('#new-project-path').value.trim()||undefined,api_base_url:$('#llm-base-url').value.trim(),model:$('#llm-model').value.trim()});backend.projects=(await VoiceBookAPI.listProjects()).projects||[];closeLayer();await loadProject(p.id);toast('项目已创建')}catch(e){toast(e.message,true)}};
$('#save-project-settings').onclick=async()=>{try{if(!backend.online)throw new Error('后端未连接');backend.project=await VoiceBookAPI.updateProjectSettings(backend.projectId,{api_base_url:$('#llm-base-url').value.trim(),model:$('#llm-model').value.trim(),generation_mode:$('#generation-mode').value,interval_ms:Number($('#interval-ms').value)||450});closeLayer();toast('项目设置已保存')}catch(e){toast(e.message,true)}};
$$('[data-scroll-to]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scrollTo)?.scrollIntoView({behavior:'smooth'}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLayer();$('#sidebar').classList.remove('open')}});
renderChapters();renderScript();renderVoiceDrawer();renderEpisodeVoices();buildWaveform();initializeBackend();
